version: '3.4'

services:
  web:
    build: .
    ports:
      - "80:80"
      - "443:443"
    environment:
      ConnectionStrings__DefaultConnection: "Data Source=/app/MyDatabase.db;"
    depends_on:
      - db

  db:
    image: sqlite
    volumes:
      - ./data:/data
    environment:
      DB_CONNECTION_STRING: "Data Source=/data/MyDatabase.db"