version: '3.4'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Data Source=/app/data/MyDatabase.db;"
    volumes:
      - ./data:/app/data