// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiRest_Safra.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240716032501_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiRest_Safra.Models.DbContext.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Client_Id")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Company_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Client_Id");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("ApiRest_Safra.Models.DbContext.Bill_Product", b =>
                {
                    b.Property<int>("Bill_Id")
                        .HasColumnType("int");

                    b.Property<int>("Product_Id")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("Bill_Id", "Product_Id");

                    b.HasIndex("Product_Id");

                    b.ToTable("Bill_Product");
                });

            modelBuilder.Entity("ApiRest_Safra.Models.DbContext.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("ApiRest_Safra.Models.DbContext.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("ApiRest_Safra.Models.DbContext.User", b =>
                {
                    b.Property<int>("UsrUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsrUserId"));

                    b.Property<string>("UsrEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsrPass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsrUserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("ApiRest_Safra.Models.DbContext.Bill", b =>
                {
                    b.HasOne("ApiRest_Safra.Models.DbContext.Client", "Client")
                        .WithMany("Bills")
                        .HasForeignKey("Client_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("ApiRest_Safra.Models.DbContext.Bill_Product", b =>
                {
                    b.HasOne("ApiRest_Safra.Models.DbContext.Bill", "Bill")
                        .WithMany("Bill_Products")
                        .HasForeignKey("Bill_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiRest_Safra.Models.DbContext.Product", "Product")
                        .WithMany("Bill_Products")
                        .HasForeignKey("Product_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ApiRest_Safra.Models.DbContext.Bill", b =>
                {
                    b.Navigation("Bill_Products");
                });

            modelBuilder.Entity("ApiRest_Safra.Models.DbContext.Client", b =>
                {
                    b.Navigation("Bills");
                });

            modelBuilder.Entity("ApiRest_Safra.Models.DbContext.Product", b =>
                {
                    b.Navigation("Bill_Products");
                });
#pragma warning restore 612, 618
        }
    }
}
